// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"basic-microservice/hello/models"
)

// ListProductsReader is a Reader for the ListProducts structure.
type ListProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProductsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewListProductsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewListProductsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewListProductsNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListProductsOK creates a ListProductsOK with default headers values
func NewListProductsOK() *ListProductsOK {
	return &ListProductsOK{}
}

/* ListProductsOK describes a response with status code 200, with default header values.

A list of products
*/
type ListProductsOK struct {
	Payload []*models.Product
}

func (o *ListProductsOK) Error() string {
	return fmt.Sprintf("[GET /][%d] listProductsOK  %+v", 200, o.Payload)
}
func (o *ListProductsOK) GetPayload() []*models.Product {
	return o.Payload
}

func (o *ListProductsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProductsCreated creates a ListProductsCreated with default headers values
func NewListProductsCreated() *ListProductsCreated {
	return &ListProductsCreated{}
}

/* ListProductsCreated describes a response with status code 201, with default header values.

No content is returned by this API endpoint
*/
type ListProductsCreated struct {
}

func (o *ListProductsCreated) Error() string {
	return fmt.Sprintf("[GET /][%d] listProductsCreated ", 201)
}

func (o *ListProductsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListProductsNotFound creates a ListProductsNotFound with default headers values
func NewListProductsNotFound() *ListProductsNotFound {
	return &ListProductsNotFound{}
}

/* ListProductsNotFound describes a response with status code 404, with default header values.

Generic error message returned as a string
*/
type ListProductsNotFound struct {
	Payload *models.GenericError
}

func (o *ListProductsNotFound) Error() string {
	return fmt.Sprintf("[GET /][%d] listProductsNotFound  %+v", 404, o.Payload)
}
func (o *ListProductsNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *ListProductsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProductsNotImplemented creates a ListProductsNotImplemented with default headers values
func NewListProductsNotImplemented() *ListProductsNotImplemented {
	return &ListProductsNotImplemented{}
}

/* ListProductsNotImplemented describes a response with status code 501, with default header values.

Generic error message returned as a string
*/
type ListProductsNotImplemented struct {
	Payload *models.GenericError
}

func (o *ListProductsNotImplemented) Error() string {
	return fmt.Sprintf("[GET /][%d] listProductsNotImplemented  %+v", 501, o.Payload)
}
func (o *ListProductsNotImplemented) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *ListProductsNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
